// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdahbxyxmhbxfjwuystd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkYWhieHl4bWhieGZqd3V5c3RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzcxOTAsImV4cCI6MjA2NTc1MzE5MH0.XU2h6qvbaol98hTfHYVdwDbutEns6Q0m7YgcK9aXr30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);