// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnoclpsyagfgfgfrnnmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZub2NscHN5YWdmZ2ZnZnJubm15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyOTgwODksImV4cCI6MjA2NTg3NDA4OX0.pN2FRO_moV5Civzuxr79_U268IvvFoNsacVcGSK1tow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);